version: "3.1"
services:
  elasticsearch:
    image: elastic.m.daocloud.io/elasticsearch/elasticsearch:8.14.3
    restart: always
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    image: elastic.m.daocloud.io/kibana/kibana:8.14.3
    restart: always
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch